### ISSUE TITLE
 How to test with PoinTr on my  own dataset?

### ISSUE THREAD

**Issue by JANEKKO** [yuxumin/PoinTr#11]
Thanks a lot for your commit, could you please give some ideas on how to test with PoinTr on my  own dataset?

**Comment by blukaz** [comment]
Hi yuxumin,

Thanks for the insights, but I get the following error:
`Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    run_net(args, config, train_writer, val_writer)
  File "/content/drive/MyDrive/ColabNotebooks/PoinTr_setup/PoinTr/tools/runner.py", line 17, in run_net
    (train_sampler, train_dataloader), (_, test_dataloader) = builder.dataset_builder(args, config.dataset.train), \
  File "/content/drive/MyDrive/ColabNotebooks/PoinTr_setup/PoinTr/tools/builder.py", line 14, in dataset_builder
    dataset = build_dataset_from_cfg(config._base_, config.others)
  File "/content/drive/MyDrive/ColabNotebooks/PoinTr_setup/PoinTr/datasets/build.py", line 16, in build_dataset_from_cfg
    return DATASETS.build(cfg, default_args = default_args)
  File "/content/drive/MyDrive/ColabNotebooks/PoinTr_setup/PoinTr/utils/registry.py", line 148, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/content/drive/MyDrive/ColabNotebooks/PoinTr_setup/PoinTr/utils/registry.py", line 282, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SIW is not in the dataset registry'`

It seems that my custom dataset doesn't get loaded into the registry:
`Registry(name=dataset, items={'KITTI': <class 'datasets.KITTIDataset.KITTI'>, 'PCN': <class 'datasets.PCNDataset.PCN'>, 'ShapeNet': <class 'datasets.ShapeNet55Dataset.ShapeNet'>})`

I tried to debug it in the registry.py script, but I couldn't figure out what the problem is. In line 270 it merges the new config successfully and then gets kicked out at 278. 

Note: I've added the dataset config file, model config file and the python script in the datasets folder.

Thanks in advance!

**Comment by yuxumin** [comment]
@blukaz Have you initialized your dataset class in the `datatsets/__init__.py'？

**Comment by blukaz** [comment]
@yuxumin Thanks! That did the job

**Comment by blukaz** [comment]
Here is are some additional steps for others who are trying to **train** the PoinTr model on their own (custom) dataset:

- add this line in the ".datasets/__init__.py" script: `import datasets.CUSTOMDATASETNAME`
- add the support for your dataset in the ".tools/runner.py" script: take a look at line 82 in the code
- optional: if you need support for ".ply" files then you have to add this in ".datasets/io.py" script

**Comment by zura-false** [comment]
> Here is are some additional steps for others who are trying to **train** the PoinTr model on their own (custom) dataset:
> 
> * add this line in the ".datasets/**init**.py" script: `import datasets.CUSTOMDATASETNAME`
> * add the support for your dataset in the ".tools/runner.py" script: take a look at line 82 (def run_net) and line 178 (def validate) in the code
> * optional: if you need support for ".ply" files then you have to add this in ".datasets/io.py" script
> * important: don't forget to center and normalize your point cloud data

Excuse me, have you tried training this model on a dataset of large outdoor buildings

**Comment by JANEKKO** [comment]
【自动回复】已收到邮件。
