### ISSUE TITLE
Training error: ModuleNotFoundError: No module named 'pointnet2_ops'

### ISSUE THREAD

**Issue by husnejahan** [yuxumin/PoinTr#136]
Hi 
I am getting error during training. bash ./scripts/train.sh 0     --config ./cfgs/PCN_models/PoinTr.yaml     --exp_name example

from pointnet2_ops import pointnet2_utils
ModuleNotFoundError: No module named 'pointnet2_ops'

I tried ti install:

pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
Collecting pointnet2_ops

**Comment by husnejahan** [comment]
Hi,
I have solved by adding manually this repo in extensions folder then Run 
python setup.py install --user manually under each dependency directory 

[pointnet2_ops_lib.zip](https://github.com/yuxumin/PoinTr/files/13322336/pointnet2_ops_lib.zip)

**Comment by ybhhdt** [comment]
Thanks

**Comment by proshantkulkarni** [comment]
> Hi, I have solved by adding manually this repo in extensions folder then Run python setup.py install --user manually under each dependency directory
> 
> [pointnet2_ops_lib.zip](https://github.com/yuxumin/PoinTr/files/13322336/pointnet2_ops_lib.zip)

I exactly did as said, 
I'm facing this error,
Help please.

nvcc fatal   : Unsupported gpu architecture 'compute_37'
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1

**Comment by ybhhdt** [comment]
您好，您的信息我已收到

**Comment by one2clouds** [comment]
I have solved the problem of : 
```nvcc fatal : Unsupported gpu architecture 'compute_37'```

Turns out, the error is due to the GPU compatibility problem. Current GPU CUDA installation doesn't support older GPU architecture which support 'compute_37'

First check for CUDA version in the terminal using 
```
nvcc --version
```

Specs needed for download CUDA toolkit can be found using code below : 
```
nvidia-smi -L
uname -a
lsb_release -a
```

You can install recent CUDA version, CUDA 12.8 (as of now) and set up path in .bashrc file. 
Check if correctly build or not using this github repo : 
```https://github.com/NVIDIA/cuda-samples/tree/master```
But even after built, we get same CUDA error. 

Because of CUDA incompatibility problem, remove CUDA you just downloaded, 
Then, download 11.8 version. 
Install pytorch for CUDA-11.8 using : ```https://github.com/vllm-project/vllm/issues/1453```

Remove virtualenv, set up a new one and do all the process again. This solves your problem. 

![Image](https://github.com/user-attachments/assets/0bb8e6d1-6125-4fb6-a56a-d8c704b3b713)

**Comment by ybhhdt** [comment]
您好，您的信息我已收到

**Comment by one2clouds** [comment]
https://github.com/erikwijmans/Pointnet2_PyTorch/issues/180

You can follow this thread to resolve this error.

**Comment by ybhhdt** [comment]
您好，您的信息我已收到
