### ISSUE TITLE
Support for CPU

### ISSUE THREAD

**Issue by chang-github-00** [yuxumin/PoinTr#41]
Hi,
     Macbook can't use cuda  and the chamfer distance requires cuda to install. How can I use a cpu version? 
     Thank you!

**Comment by yuxumin** [comment]
Hello,

Public source codes can now only be run in the CUDA environment. However, you can get it running in a CPU environment with a few simple steps:

Train the model on the *cpu* environment:
 - Download torch for cpu.
 - Remove action to convert `Tensor` or `Module` into `cuda.Tensor` or `cuda.Module`
 - Use python (instead of cuda) based CD metrics. For example https://github.com/ThibaultGROUEIX/ChamferDistancePytorch/blob/master/chamfer_python.py#L31
(I don't recommend you to train the model on CPU because the training time is too long)

To evaluate the model in the *cpu* environment:
 - Download torch for cpu.
 - Remove action to convert `Tensor` or `Module` into `cuda.Tensor` or `cuda.Module`
 - No installation for CD required. (comment out the code that computes the CD in the inference phase)

Best regards!

**Comment by chang-github-00** [comment]
Many thanks!

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist

**Comment by JiangZhenW** [comment]
hi, my GPU have enough memory, but why i meet this eror:cannot allocate memory? thank you for your reply
